function CardShell({
  badge,
  children,
  caption,
}: {
  badge: string
  children: React.ReactNode
  caption: string
}) {
  return (
    <div className="overflow-hidden rounded-2xl border border-slate/10 bg-panel shadow-sm">
      <div className="h-1.5 w-full bg-brand" />
      <div className="p-6">
        <span className="inline-block rounded-full bg-brand/10 px-3 py-1 text-xs font-bold text-brand">
          {badge}
        </span>
        <div className="mt-5">{children}</div>
        <p className="mt-5 text-sm font-medium text-slate/70">{caption}</p>
      </div>
    </div>
  )
}

export function WorkSamples() {
  return (
    <section className="bg-panel py-24 lg:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-10">
        <div className="max-w-3xl">
          <h2 className="text-balance text-4xl font-bold tracking-tight text-slate md:text-5xl">
            Real output. Real <span className="text-magenta">results.</span>
          </h2>
          <p className="mt-5 text-lg leading-relaxed text-slate/75 md:text-xl">
            Every asset below was generated by Kaleiora&apos;s Creative Agent —
            no human copywriter, no designer, no brief rewrites.
          </p>
        </div>

        <div className="mt-14 grid gap-6 lg:grid-cols-3">
          {/* Instagram post mockup */}
          <CardShell
            badge="Creative Agent — Instagram 1080x1080"
            caption="Apex Strength Co — generated in 30 seconds"
          >
            <div className="overflow-hidden rounded-xl bg-cool">
              <div className="flex aspect-square flex-col justify-center px-7">
                <p className="text-3xl font-extrabold leading-tight tracking-tight text-slate">
                  STOP FUELING <span className="text-magenta">AVERAGE.</span>
                </p>
                <div className="mt-3 h-1 w-24 bg-magenta" />
              </div>
              <div className="flex items-center justify-between bg-brand px-7 py-4">
                <span className="text-sm font-bold uppercase tracking-wide text-white">
                  Earn it. Every rep.
                </span>
                <span className="text-xs font-medium text-white/80">
                  apexstrength.co
                </span>
              </div>
            </div>
          </CardShell>

          {/* Ad copy */}
          <CardShell
            badge="Creative Agent — Meta Ad"
            caption="Competitor contrast ad — Quality Gate approved"
          >
            <div className="rounded-xl bg-cool p-6">
              <p className="text-xl font-bold leading-snug text-slate">
                Ghost has the hype. Apex has the results.
              </p>
              <p className="mt-4 leading-relaxed text-slate/80">
                Stop paying for marketing. Start paying for performance. Apex
                Strength — formulated for men who train for keeps. Free shipping
                on first order.
              </p>
            </div>
          </CardShell>

          {/* Email */}
          <CardShell
            badge="Creative Agent — Email"
            caption="Target open rate: 38%"
          >
            <div className="rounded-xl bg-cool p-6">
              <p className="text-xs font-semibold uppercase tracking-widest text-brand">
                Subject
              </p>
              <p className="mt-1 text-lg font-bold leading-snug text-slate">
                You don&apos;t need more motivation. You need better fuel.
              </p>
              <p className="mt-4 text-sm leading-relaxed text-slate/80">
                Most pre-workouts give you jitters and a crash. Apex gives you
                90 minutes of locked-in focus. Here&apos;s why the formula is
                different...
              </p>
            </div>
          </CardShell>
        </div>

        <p className="mt-10 text-center text-sm font-semibold text-brand">
          All assets validated by Quality Gate. Brand Health Score: 91.
        </p>
      </div>
    </section>
  )
}
